/**
 *  A header to include on each of the generated files.
 */
export const FILE_HEADER = `/* eslint-disable */
/**
* This file was automatically generated by @laeri/config-generator.
* DO NOT MODIFY IT BY HAND. Instead, modify the config.yml file, and
* run the @laeri/config-generator generate CLI script to regenerate this file.
*/`
